### ISSUE TITLE
Request for Guidance: Building Project for Testing and Evaluation

### ISSUE THREAD

**Issue by DanielDoe** [vivianross06/HoloLens-Eye-Tracking#1]
I hope this message finds you well. I recently came across your project on GitHub, titled HoloLens-Eye-Tracking, and I must say, I am very impressed with the work you have done. The project looks promising, and I am keen to test and evaluate it further.

I would greatly appreciate it if you could provide some guidance on how to build the project on my local device. I would like to set it up, explore its features, and possibly contribute to its development. As a developer, I believe that hands-on testing and evaluation are essential in gaining a deeper understanding of a project's capabilities and potential areas for improvement. Could you please provide me with some guidance on the necessary steps and dependencies required to successfully build the project?

I am comfortable working with unity and c# and have experience setting up similar projects in the past. However, any additional information or specific instructions you can provide would be immensely helpful.

Thank you for your time and consideration. I am genuinely excited about your project and look forward to exploring it further. Please let me know if there is any additional information or assistance you may require from my end.

Best regards,

**Comment by vivianross06** [comment]
Hello, thank you for reaching out. I have added a Readme to the project, which currently outlines basic build steps and includes relevant links from the Microsoft documentation regarding build steps. The build steps are pretty standard as far as building a Unity project for the HoloLens 2, so anybody with prior experience with this should have no problem building and deploying this project.

I am planning to slowly add a usage guide to the Readme as well. The basic gist of it is that once you open the deployed app, you should be able to use the numbers 1-6 on a connected Bluetooth keyboard to start one of 6 evaluation tasks. After the task is complete, you should be able to pull eye tracking log data from the device portal via the File Explorer. I am planning to add a more detailed description to the Readme.

**Comment by DanielDoe** [comment]
Thank you for your prompt response to my inquiry regarding building the project. I appreciate your willingness to assist me in exploring and evaluating your project further.

Based on your response, I will follow the instructions provided in the README.md file to set up and run the project on my local device. I am confident that the information outlined in the README.md will guide me through the necessary steps and dependencies required for a successful build.

I want to express my gratitude for your support and for developing such an intriguing project. I believe that by actively testing and evaluating the functionality and features, we can contribute to its enhancement and overall success.

If at any point during my exploration of the project, I come across any questions or encounter issues, I will not hesitate to reach out to you for guidance. I genuinely appreciate your willingness to provide assistance and support.

Once again, thank you for your response and for sharing your remarkable project with the community. I look forward to the exciting journey ahead, and I am eager to see how I can contribute to its development.

Wishing you continued success and innovation. Please feel free to reach out if you require any future assistance or support.

Best regards,
